import { AssignmentEventType, AssignmentStatus, ChoreHistoryAction, FrequencyType, SourceChannel } from '@prisma/client'
import { prisma } from '@/lib/db'
import { computeNextDueAfter } from '@/lib/recurrence'

type SchedulerResult = {
  scanned: number
  created: number
  skippedWithPending: number
  skippedNotDue: number
  skippedMissingAssignee: number
}

export async function generateDueAssignments(now: Date = new Date()): Promise<SchedulerResult> {
  const chores = await prisma.chore.findMany({
    where: {
      isActive: true,
      frequencyType: {
        not: FrequencyType.AS_NEEDED,
      },
    },
    orderBy: {
      createdAt: 'asc',
    },
  })

  const summary: SchedulerResult = {
    scanned: chores.length,
    created: 0,
    skippedWithPending: 0,
    skippedNotDue: 0,
    skippedMissingAssignee: 0,
  }

  for (const chore of chores) {
    const dueDate = chore.nextDueAt ?? now

    if (!chore.defaultAssigneeId) {
      summary.skippedMissingAssignee += 1
      continue
    }

    if (dueDate > now) {
      summary.skippedNotDue += 1
      continue
    }

    const hasPending = await prisma.choreAssignment.findFirst({
      where: {
        choreId: chore.id,
        status: AssignmentStatus.PENDING,
      },
      select: { id: true },
    })

    if (hasPending) {
      summary.skippedWithPending += 1

      const nextDueAt = computeNextDueAfter({
        currentDue: dueDate,
        now,
        frequencyType: chore.frequencyType,
        frequencyValue: chore.frequencyValue,
      })

      await prisma.chore.update({
        where: { id: chore.id },
        data: { nextDueAt },
      })

      continue
    }

    await prisma.$transaction(async (tx) => {
      const assignment = await tx.choreAssignment.create({
        data: {
          choreId: chore.id,
          assignedToId: chore.defaultAssigneeId!,
          dueDate,
          status: AssignmentStatus.PENDING,
        },
      })

      await tx.assignmentEvent.create({
        data: {
          assignmentId: assignment.id,
          actorUserId: null,
          eventType: AssignmentEventType.CREATED,
          sourceChannel: SourceChannel.SYSTEM,
          metadata: {
            scheduler: 'generateDueAssignments',
          },
        },
      })

      await tx.choreHistory.create({
        data: {
          choreId: chore.id,
          userId: chore.defaultAssigneeId!,
          action: ChoreHistoryAction.ASSIGNED,
          assignmentId: assignment.id,
          notes: 'Automatically generated by scheduler.',
        },
      })

      const nextDueAt = computeNextDueAfter({
        currentDue: dueDate,
        now,
        frequencyType: chore.frequencyType,
        frequencyValue: chore.frequencyValue,
      })

      await tx.chore.update({
        where: { id: chore.id },
        data: { nextDueAt },
      })
    })

    summary.created += 1
  }

  return summary
}
